<?php

	/** Generated by Sirius */

	namespace flash\filters;


	class GlowFilter extends \sirius\SiriusObject {

		public $alpha;

		public $blurX;

		public $blurY;

		public $color;

		public $inner;

		public $knockout;

		public $quality;

		public $strength;

		public function __construct($alpha, $blurX, $blurY, $color, $inner, $knockout, $quality, $strength){
			$this->alpha = $alpha;
			$this->blurX = $blurX;
			$this->blurY = $blurY;
			$this->color = $color;
			$this->inner = $inner;
			$this->knockout = $knockout;
			$this->quality = $quality;
			$this->strength = $strength;
		}

	}
