<?php

	/** Generated by Sirius */

	namespace flash\filters;


	class GlowFilter extends \sirius\SiriusObject {

		public $alpha;

		public $blurX;

		public $blurY;

		public $color;

		public $inner;

		public $knockout;

		public $quality;

		public $strength;

		public function __construct(){
		}

	}
